Guidelime.registerGuide([[
[GA Alliance][N1-20Azuremyst Isle to Bloodmyst Isle][NX19-21Redridge Mountains]
Accept [QA9279 You Survived!] from Megelon
Turn in [QT9279 You Survived!] to Proenitus and accept [QA9280 Replenishing the Healing Crystals].
Talk to Botanist Taerix and accept [QA10302 Volatile Mutations]
Kill Volatile Mutations and Vale Moths for [QC9280 Replenishing the Healing Crystals] and [QC10302 Volatile Mutations]
Reach level [XP2]
Talk to Proenitus to turn in [QT9280 Replenishing the Healing Crystals] and accept [QA9409 Urgent Delivery!]
Talk to Zalduun to turn in [QT9409 Urgent Delivery!] and accept [QA9283 Rescue the Survivors!]
Talk to Firmanvaar to accept and turn in [QA9421 Shaman Training][QT9421 Shaman Training] and train [A Shaman]
Talk to Proenitus to accept and turn in [QA9289 Warrior Training][QT9289 Warrior Training] and train [A Warrior]
Talk to Aurelon to accept and turn in [QA9287 Paladin Training][QT9287 Paladin Training] and train [A Paladin]
Talk to Keilnei to accept and turn in [QA9288 Hunter Training][QT9288 Hunter Training] and train [A Hunter]
Talk to Valaatu to accept and turn in [QA9290 Mage Training][QT9290 Mage Training] and train [A Mage]
Talk to Zalduun to accept and turn in [QA9291 Priest Training][QT9291 Priest Training] and train [A Priest]
Talk to Proenitus to accept [QA9371 Botanist Taerix]
Talk to Botanist Taerix to turn in [QT10302 Volatile Mutations] and [QT9371 Botanist Taerix]. Accept [QA9293 What Must Be Done...]
Talk to Apprentice Vishael and accept [QA9799 Botanical Legwork]
Talk to Technician Zhanaa and accept [QA9305 Spare Parts]
Talk to Vindicator Aldar and accept [QA9303 Inoculation]
Use Gift of the Naaru ability on a Draenei Survivor for [QC9283 Rescue the Survivors!]
Kill Mutated Root Lashers for [QC9293 What Must Be Done...] and collect Corrupted Flowers for [QC9799 Botanical Legwork]
Talk to Zalduun to turn in [QT9283 Rescue the Survivors!]
Talk to Botanist Taerix to turn in [QT9293 What Must Be Done...] and accept [QA9294 Healing the Lake].
Talk to Apprentice Vishael to turn in [QT9799 Botanical Legwork]
Reach level [XP3]
Use Neutralizing Agent at the crystal in the lake for [QC9294 Healing the Lake]
Go to the cave and complete [QC9305 Spare Parts] and [QC9303 Inoculation]
Talk to Vindicator Aldar to turn in [QT9303 Inoculation] and accept [QA9309 The Missing Scout]
Talk to Technician Zhanaa to turn in [QT9305 Spare Parts]
Reach level [XP4]
Talk to Firmanvaar to accept [QA9449 Call of Earth][A Shaman]
Talk to Botanist Taerix to turn in [QT9294 Healing the Lake]
Talk to Spirit of the Vale to turn in [QT9449 Call of Earth] and accept [QA9450 Call of Earth]
Kill Restless Spirit of Earth for [QC9450 Call of Earth]
Talk to Spirit of the Vale to turn in [QT9450 Call of Earth] and accept [QA9451 Call of Earth]
Talk to Firmanvaar to turn in [QT9451 Call of Earth]
Talk to Tolaan to turn in [QT9309 The Missing Scout] and accept [QA10303 The Blood Elves]
Kill Blood Elf Scouts for [QC10303 The Blood Elves]
Talk to Tolaan to turn in [QT10303 The Blood Elves] and accept [QA9311 Blood Elf Spy]
Kill Surveyor Candress for [QC9311 Blood Elf Spy] and loot Blood Elf Plans
Accept [QA9798 Blood Elf Plans] in your bag
Talk to Vindicator Aldar and turn in [QT9311 Blood Elf Spy] and accept [QA9312 The Emitter]. Turn in [QT9798 Blood Elf Plans].
Reach level [XP6]
Talk to Technician Zhanaa and turn in [QT9312 The Emitter] and accept [QA9313 Travel to Azure Watch]
Talk to Aeun to accept [QA9314 Word From Azure Watch]
Talk to Diktynna and accept [QA9452 Red Snapper - Very Tasty!]
Use the Draenei Fishing Net on Red Snapper Schools for [QC9452 Red Snapper - Very Tasty!]
Talk to Diktynna to turn in [QT9452 Red Snapper - Very Tasty!] and accept [QA9453 Find Acteon!]
Talk to Acteon to turn in [QT9453 Find Acteon!]. Accept [QA9454 The Great Moongraze Hunt].
Talk to Anchorite Fateema to accept [QA9463 Medicinal Purpose].
Talk to Technician Dyvuun to turn in [QT9313 Travel to Azure Watch].
Talk to Caregiver Chellan to turn in [QT9314 Word from Azure Watch]. Make this inn your home [S].
Talk to Admiral Odesyus to accept [QA9506 A Small Start]
Talk to "Cookie" McWeaksauce to accept [QA9512 Cookie's Jumbo Gumbo].
Kill Skittering Crawlers for [QC9512 Cookie's Jumbo Gumbo][O], Root Trappers for [QC9463 Medicinal Purpose][O], and Moongraze Stags for [QC9454 The Great Moongraze Hunt][O] while doing the next part
Get the Nautical Map for [QC9506,2 A Small Start]
Get the Nautical Compass for [QC9506,1 A Small Start]
Finish up [QC9512 Cookie's Jumbo Gumbo], [QC9463 Medicinal Purpose], and [QC9454 The Great Moongraze Hunt].
Reach level [XP7]
Talk to "Cookie" McWeaksauce to turn in [QT9512 Cookie's Jumbo Gumbo]
Talk to Admiral Odesyus to turn in [QT9506 A Small Start] and accept [QA9530 I've Got a Plant]
Talk to Priestess Kyleen Il'dinare to accept [QA9513 Reclaiming the Ruins]
Talk to Archaelogist Adamant Ironheart to accept [QA9523 Precious and Fragile Things Need Special Handling]
Click Hollowed Out Tree for [QC9530,1 I've Got a Plant]
Click Pile of Leaves for [QC9530,2 I've Got a Plant]
Talk to Admiral Odesyus to turn in [QT9530 I've Got a Plant] and accept [QA9531 Tree's Company]
Kill naga for [QC9513 Reclaiming the Ruins]
When Rune Covered Tablet drops, click it to accept [QA9514 Rune Covered Tablet]
Click Ancient Relics for [QC9523 Precious and Fragile Things Need Special Handling]
Use the Tree Disguise Kit at the flag in Traitor's Cove for [QC9531 Tree's Company]
Die and resurrect at the spirit healer
Reach level [XP8]
Talk to Anchorite Fateema to turn in [QT9463 Medicinal Purpose]
Talk to Daedal to accept [QA9473 An Alternative Alternative]
Talk to Dulvi to accept [QA10428 The Missing Fisherman]
Talk to Cryptographer Aurren to accept [QA9538 Learning the Language]
Use the Stillpine Furbolg Language Primer in your bag for [QC9538 Learning the Language]
Click Totem of Akida to turn in [QT9538 Learning the Language] and accept [QA9539 Totem of Coo]
Talk to Acteon to turn in [QT9454 The Great Moongraze Hunt] and accept [QA10324 The Great Moongraze Hunt]
Talk to Admiral Odesyus to turn in [QT9531 Tree's Company] and accept [QA9537 Show Gnomercy]
Talk to Priestess Kyleen Il'dinare to turn in [QT9513 Reclaiming the Ruins] and [QT9514 Rune Covered Tablet]. Accept [QA9515 Warlord Sriss'tiz].
Talk to Archaelogist Adamant Ironheart to turn in [QT9523 Precious and Fragile Things Need Special Handling]
Talk to Engineer "Spark" Overgrind and kill and loot him for [QC9537 Show Gnomercy]
Talk to Admiral Odesyus to turn in [QT9537 Show Gnomercy]. Accept [QA9602 Deliver Them From Evil...]
Kill Warlord Sriss'tiz for [QC9515 Warlord Sriss'tiz] 
Talk to Cowlen to turn in [QT10428 The Missing Fisherman] and accept [QA9527 All That Remains]
Kill Owlbeasts and loot them for [QC9527 All That Remains]
Talk to Cowlen to turn in [QT9527 All That Remains]
OPTIONAL GROUP QUEST - Talk to Magwin to accept [QA9528 A Cry for Help]
Escort Magwin for [QC9528 A Cry for Help]
Talk to Cowlen to turn in [QT9528 A Cry for Help]
Turn in [QT9515 Warlord Sriss'tiz] at Priestess Kyleen Il'dinare
Talk to Exarch Menelaous to turn in [QT9602 Deliver Them From Evil...]
Kill Moongraze Bucks for [QC10324 The Great Moongraze Hunt]
Talk to Totem of Coo to turn in [QT9539 Totem of Coo] and accept [QA9540 Totem of Tikti]
Talk to Totem of Tikti to turn in [QT9540 Totem of Tikti] and accept [QA9541 Totem of Yor]
Talk to Totem of Yor to turn in [QT9541 Totem of Yor] and accept [QA9542 Totem of Vark]
Talk to Totem of Vark to turn in [QT9542 Totem of Vark] and accept [QA9544 The Prophecy of Akida]
Kill Bristlelimb mobs to loot Bristlelimb Keys. Use them to open the cages nearby for [QC9544 The Prophecy of Akida]
Hearth to Azure Watch [H]
Talk to Arugoo of the Stillpine to turn in [QT9544 The Prophecy of Akida] and accept [QA9559 Stillpine Hold]
Collect Azure Snapdragon Bulbs for [QC9473 An Alternative Alternative]
Talk to Daedal to turn in an [QT9473 Alternative Alternative]
Talk to Acteon to turn in [QT10324 The Great Moongraze Hunt]
Reach level [XP10]
Talk to Ruada to accept [QA9582 Strength of One][A Warrior]
Talk to Tuluun to accept [QA9464 Call of Fire][A Shaman]
Talk to Semid to accept [QA9595 Control][A Mage]
Talk to Acteon to accept [QA9757 Seek Huntress Kella Nightbow][A Hunter]
Talk to Huntress Kella Nightbow to turn in [QT9757 Seek Huntress Kella Nightbow] and accept [QA9591 Taming the Beast][A Hunter]
[G19,64,5Azuremyst Isle]Head south along the beach to around here and use the Taming Totem on a Barbed Crawler for [QC9591 Taming the Beast][A Hunter]
Talk to Huntress Kella Nightbow to turn in [QT9591 Taming the Beast] and accept [QA9592 Taming the Beast][A Hunter]
[G36,34,5Azuremyst Isle]Head here and use the Taming Totem on a Greater Timberstrider for [QC9592 Taming the Beast][A Hunter]
Talk to Huntress Kella Nightbow to turn in [QT9592 Taming the Beast] and accept [QA9593 Taming the Beast][A Hunter]
[G36,40,5Azuremyst Isle]Head here and use the Taming Totem on a Nightstalker for [QC9593 Taming the Beast][A Hunter]
Talk to Huntress Kella Nightbow to turn in [QT9593 Taming the Beast] and accept [QA9675 Beast Training][A Hunter]
Go into The Exodar and talk to Ganaar to turn in [QT9675 Beast Training][A Hunter]
Talk to Exarch Menelaous to accept [QA9623 Coming of Age]
Use the Ravager Cage Key to unlock the cage and kill the Death Ravager for [QC9582 Strength of One][A Warrior]
Talk to Temper to turn in [QT9464 Call of Fire] and accept [QA9465 Call of Fire]
Talk to High Chief Stillpine to turn in [QT9559 Stillpine Hold]
Talk to Gurf to accept [QA9562 Murlocs... Why Here? Why Now?]
Talk to Moordo to accept [QA9560 Beasts of the Apocalypse!]
Kill murlocs until Quel'dorei Magewraith appears and kill it for [QC9595 Control][A Mage]
Kill Murgurgula and loot Gurf's Dignity. Use it to accept [QA9564 Gurf's Dignity]
Kill Siltfin enemies and loot Stillpine Grain for [QC9562 Murlocs... Why Here? Why Now?]
Talk to Gurf to turn in [QT9562 Murlocs... Why Here? Why Now?] and [QT9564 Gurf's Dignity].
Talk to High Chief Stillpine to accept [QA9565 Search Stillpine Hold]
Talk to Stillpine the Younger to accept [QA9573 Chieftain Oomooroo]
Click Blood Crystal to turn in [QT9565 Search Stillpine Hold] and accept [QA9566 Blood Crystals]
While doing the next steps kill Crazed Wildkin for [QC9465 Call of Fire][O]
Kill Crazed Wildkin for [QC9573,2 Chieftain Oomooroo] 
Kill Crazed Wildkin for [QC9465 Call of Fire]
Kill Chieftain Oomooroo for [QC9573,1 Chieftain Ooomooroo]
Talk to High Chief Stillpine to turn in [QT9566 Blood Crystals]
Talk to Stillpine the Younger to turn in [QT9573 Chieftain Oomooroo]
Reach level [XP11]
Talk to Kurz the Revelator to accept [QA9570 The Kurken is Lurkin']
Kill The Kurken for [QC9570 The Kurken is Lurkin']
Talk to Kurz the Revelator to turn in [QT9570 The Kurken is Lurkin'] and accept [QA9571 The Kurken's Hide]
Talk to High Chief Stillpine to accept [QA9622 Warn Your People]
Talk to Moordo to turn in [QT9571 The Kurken's Hide]
Kill Ravager Specimens for [QC9560 Beasts of the Apocalypse!]
Talk to Temper to turn in [QT9465 Call of Fire] and accept [QA9467 Call of Fire] [A Shaman]
Talk to Moordo to turn in [QT9560 Beasts of the Apocalypse!]
Talk to Exarch Menelaous to turn in [QT9622 Warn Your People]
Talk to Ruada to turn in [QT9582 Strength of One] and accept [QA10350 Behomat][A Warrior]
Talk to Torallius the Pack Handler to turn in [QT9623 Coming of Age] and accept [QA9625 Elekks Are Serious Business]
Go into The Exodar and talk to Behomat to turn in [QT10350 Behomat][A Warrior]
Go into the Exodar and talk to Bati to turn in [QT9595 Control][A Mage]
[G 11,82,1 Azuremyst Isle] Go to this effigy and open the Fireproof Satchel. Use the Ritual Torch at the effigy to summon Hauteur.[A Shaman]
Kill Hauteur and loot for [QC9467 Call of Fire][A Shaman]
Use the Orb of Returning in your bag. [A Shaman]
Talk to Temper to turn in [QT9467 Call of Fire][A Shaman]
Talk to Temper and accept Call of Fire [QA9468 Call of Fire][A Shaman]
Hearth [H][A Shaman]
Talk to Tuluun to turn in [QT9468 Call of Fire] and accept [QA9461 Call of Fire][A Shaman]
Talk to Prophet Velen to turn in [QT9461 Call of Fire] and accept [QA9555 Call of Fire][A Shaman]
Talk to Farseer Nobundo to turn in [QT9555 Call of Fire][A Shaman]
Talk to Aonar to accept [QA9624 A Favorite Treat]
Talk to Vorkhan the Elekk Herder to turn in [QT9625 Elekks Are Serious Business] and accept [QA9634 Alien Predators]
Talk to Kessel to accept [QA9663 The Kessel Run]
Talk to High Chief Stillpine for [QC9663,1 The Kessel Run]
Talk to Exarch Menelaous for [QC9663,2 The Kessel Run]
Talk to Admiral Odesyus for [QC9663,3 The Kessel Run]
Talk to Kessel to turn in [QT9663 The Kessel Run] and accept [QA9666 Declaration of Power]
Kill Bloodmyst Hatchlings for [QC9634 Alien Predators] and pick up Sand Pears for [QC9624 A Favorite Treat]
Talk to Vorkhan the Elekk Herder to turn in [QT9634 Alien Predators]
Talk to Princess Stillpine to accept [QA9667 Saving Princess Stillpine]
Kill Lord Xiz, and use the banner on his corpse for [QC9666 Declaration of Power]
[G 64.4,78.2,1 Bloodmyst Isle] Kill Bristlelimb Furbolgs around here until High Chief Bristlelimb appears
Kill High Chief Bristlelimb and loot him for The High Chief's Key [CI24099,1].
Open Princess Stillpine's Cage for [QC9667 Saving Princess Stillpine]
Talk to Kessel to turn in [QT9666 Declaration of Power] and accept [QA9668 Report to Exarch Admetius]
Talk to Aonar to turn in [QT9624 A Favorite Treat]
Click Wanted Poster to accept [QA9646 Wanted: Deathclaw]
Talk to Caregiver Topher Loaal to accept [QA9603 Beds, Bandages, and Beyond]
Talk to him again to make this inn your home. [S]
Talk to Morae to accept [QA9629 Catch and Release]
Talk to Stillpine Ambassador Frasabook to turn in [QT9667 Saving Princess Stillpine]
Talk to Jessera of Mac'Aree to accept [QA9648 Mac'Aree Mushroom Menagerie]
Talk to Laando to turn in [QT9603 Beds, Bandages, and Beyond] and accept [QA9604 On the Wings of a Hippogryph]
Fly to [F The Exodar]
Talk to Jol to accept [QA9598 Redemption][A Paladin]
Use the Tome of Divinity in you bag for [QC9598 Redemption][A Paladin]
Talk to Jol to turn in [QT9598 Redemption] and accept [QA9600 Redemption][A Paladin]
Leave The Exodar and use the Symbol of Life on the Young Furbolg Shaman for [QC9600 Redemption][A Paladin]
Go back to the Exodar to turn in [QT9600 Redemption][A Paladin]
Talk to Nurguni to turn in [QT9604 On the Wings of a Hippogryph] and accept [QA9605 Hippogryph Master Stephanos]
Talk to Stephanos to turn in [QT9605 Hippogryph Master Stephanos] and accept [QA9606 Return to Topher Loaal]
Fly to [F Blood Watch]
Talk to Caregiver Topher Loaal to turn in [QT9606 Return to Topher Loaal]
Talk to Exarch Admetius to turn in [QT9668 Report to Exarch Admetius] and accept [QA9693 What Argus Means to Me]
Talk to Harbinger Mikolaas to accept [QA9581 Learning from the Crystals]
Reach level [XP13]
Talk to Vindicator Boros to turn in [QT9693 What Argus Means to Me] and accept [QA9694 Blood Watch] and [QA9641 Irradiated Crystal Shards]
Talk to Prospector Nachlan to accept [QA10063 Explorers' League, Is That Something for Gnomes?]
Talk to Vindicator Aalesia to accept [QA9567 Know Thine Enemy]
Kill and loot creatures for [QC9641 Irradiated Crystal Shards][O] while doing the next steps
Click Aquatic Stinkhorn for [QC9648,1 Mac'Aree Mushroom Menagerie]
Use Crystal Mining Pick on Impact Site Crystal for [QC9581 Learning from the Crystals]
Click Blood Mushroom for [QC9648,2 Mac'Aree Mushroom Menagerie]
Use Murloc Tagger on Blacksilt Scouts for [QC9629 Catch and Release]
Click Fel Cone Fungus for [QC9648,4 Mac'Aree Mushroom Menagerie]
Click Nazzivus Monument Glyph for [QC9567 Know Thine Enemy]
Hearth [H]
Talk to Vindicator Aalesia to turn in [QT9567 Know Thine Enemy] and accept [QA9569 Containing the Threat]
Talk to Morae to turn in [QT9629 Catch and Release] and accept [QA9574 Victims of Corruption]
Talk to Harbinger Mikolaas to turn in [QT9581 Learning from the Crystals] and accept [QA9620 The Missing Survey Team]
Talk to Draenei Cartographer to turn in [QT9620 The Missing Survey Team] and accept [QA9628 Salvaging the Data]
Click Ruinous Polyspore for [QC9648,3 Mac'Aree Mushroom Menagerie]
Kill Wrathscale enemies for [QC9628 Salvaging the Data] and [QC9641 Irradiated Crystal Shards]
Talk to Vindicator Boros to turn in [QT9641 Irradiated Crystal Shards]
Talk to Jessera of Mac'Aree to turn in [QT9648 Mac'Aree Mushroom Menagerie]
Talk to Harbinger Mikolaas to turn in [QT9628 Salvaging the Data] and accept [QA9584 The Second Sample]
Kill Sunhawk Spies for [QC9694 Blood Watch]
Use Crystal Mining Pick on Altered Bloodmyst Crystal for [QC9584 The Second Sample]
Kill Corrupted Treants for [QC9574 Victims of Corruption]
Reach level [XP14]
Talk to Morae to turn in [QT9574 Victims of Corruption]
Talk to Harbinger Mikolaas to turn in [QT9584 The Second Sample] and accept [QA9585 The Final Sample]
Talk to Vindicator Boros to turn in [QT9694 Blood Watch] and accept [QA9779 Intercepting the Message]
Talk to Tracker Lyceon to accept [QA9643 Constrictor Vines] and [QA9580 The Bear Necessities]
Kill Sunhawk Spies for [QC9779 Intercepting the Message]
Kill Mutated Constrictors for [QC9643 Constrictor Vines]
Kill Elder Brown Bears for [QC9580 The Bear Necessities]
Talk to Vindicator Boros to turn in [QT9779 Intercepting the Message] and accept [QA9696 Translations...]
Talk to Tracker Lyceon to turn in [QT9643 Constrictor Vines] and accept [QA9647 Culling the Flutterers]. Turn in [QT9580 The Bear Necessities].
Reach level [XP15]
Talk to Morae to accept [QA9578 Searching for Galaen]
Talk to Messenger Hermesius to accept and turn in [QA9671 Urgent Delivery][QT9671 Urgent Delivery]
Go to the mailbox and get A Letter from the Admiral. Click it to accept [QA9672 The Bloodcurse Legacy].
Talk to Jessera of Mac'Aree to accept [QA9649 Ysera's Tears]
Talk to Interrogator Elysia to turn in [QT9696 Translations...] and accept [QA9698 Audience with the Prophet]
Talk to Anchorite Paetheus to accept [QA9632 Newfound Allies]
Fly to [F The Exodar]
Talk to Huntress Kella Nightbow to turn in [QT9632 Newfound Allies] and accept [QA9633 The Way to Auberdine]
Talk to Prophet Velen to turn in [QT9698 Audience with the Prophet] and accept [QA9699 Truth or Fiction]
Hearth [H]
Talk to Vindicator Boros to turn in [QT9699 Truth or Fiction] and accept [QA9700 I Shoot Magic Into the Darkness]
Kill Royal Blue Flutterers for [QC9647 Culling the Flutterers][O] while doing the next steps.
Kill Void Anomalies for [QC9700,1 I Shoot Magic Into the Darkness]
Visit Sun Portal Site for [QC9700,3 I Shoot Magic Into the Darkness]
Walk around here for [QC9700,2 I Shoot Magic Into the Darkness] if somehow you didn't complete it already
Talk to Clopper Wizbang to turn in [QT10063 Explorers' League, Is That Something for Gnomes?] and pick up [QA9548 Pilfered Equipment]. Also pick up [QA9549 Artifacts of the Blacksilt]
Kill Blacksilt Seers and Blacksilt Warriors and loot them for [QC9549 Artifacts of the Blacksilt]
Pick up Clopper's Equipment for [QC9548 Pilfered Equipment]
Kill Deathclaw for [QC9646 WANTED: Deathclaw]
Talk to Clopper Wizbang to turn in [QT9548 Pilfered Equipment] and [QT9549 Artifacts of the Blacksilt]
Use the reward Weathered Treasure Map to accept [QA9550 A Map to Where?]
Finish up [QC9647 Culling the Flutterers].
Use the Crystal Mining Pick on the Axxarien Crystal for [QC9585 The Final Sample]
Kill Axxarien Hellcallers and Axxarien Shadowstalers and pick up Corrupted Crystals for [QC9569,2 Containing the Threat][O],[QC9569,3 Containing the Threat][O],[QC9569,4 Containing the Threat][O] while doing the next step
Kill Zevrak for [QC9569,1 Containing the Threat]
Finish killing Axxarien Hellcallers and Axxarien Shadowstalers and picking up Corrupted Crystals for [QC9569,2 Containing the Threat],[QC9569,3 Containing the Threat],[QC9569,4 Containing the Threat]
Click Battered Ancient Book to turn in [QT9550 A Map to Where?] and accept [QA9557 Deciphering the Book]
Talk to Anchorite Paetheus to turn in [QT9557 Deciphering the Book] and accept [QA9561 Nolkai's Words]
Talk to Vindicator Boros to turn in [QT9700 I Shoot Magic Into the Darkness]
Talk to Vindicator Kuros to accept [QA9703 The Cryo-Core]
Talk to Tracker Lyceon to turn in [QT9647 Culling the Flutterers]
Talk to Vindicator Aalesia to turn in [QT9569 Containing the Threat]
Talk to Achelus to accept [QA9669 The Missing Expedition]
Talk to Harbinger Mikolaas to turn in [QT9585 The Final Sample] and [QT9646 WANTED: Deathclaw]. Accept [QA10064 Talk to the Hand]
Talk to Defender Adrielle to accept [QA10067 Fouled Water Spirits] and [QA10066 Oh, the Tangled Webs They Weave]
Click Mound of Dirt to turn in [QT9561 Nolkai's Words]
Talk to Prince Toreth to accept [QA9687 Restoring Sanctity]
Talk to Captain Edward Hanes to turn in [QT9672 The Bloodcurse Legacy] and accept [QA9674 The Bloodcursed Naga]
Kill Bloodcursed Naga for [QC9674 The Bloodcursed Naga]
Talk to Captain Edward Hanes to turn in [QT9674 The Bloodcursed Naga] and accept [QA9682 The Hopeless Ones...]
Kill Bloodcursed Voyagers for [QC9682 The Hopeless Ones...]
Reach level [XP17]
Talk to Captain Edward Hanes and refresh the underwater breathing buff - mark this complete
Talk to Captain Edward Hanes to turn in [QT9682 The Hopeless Ones...] and accept [QA9683 Ending the Bloodcurse]
Pick up Ysera's Tears for [QC9649 Ysera's Tears]
Click Statue of Queen Azshara and kill Atoph the Bloodcursed for [QC9683 Ending the Bloodcurse]
Talk to Captain Edward Hanes to turn in [QT9683 Ending the Bloodcurse]
Pick up Dragon Bones for [QC9687 Restoring Sanctity]
Talk to Prince Toreth to turn in [QT9687 Restoring Sanctity] and accept [QA9688 Into the Dream]
Kill Veridian Whelps and Veridian Broodlings for [QC9688 Into the Dream]
Talk to Prince Toreth to turn in [QT9688 Into the Dream]. Skip [QS9689 Razormaw].
Hearth [H]
Talk to Jessera of Mac'Aree to turn in [QT9649 Ysera's Tears]
Kill Sunhawk enemies to loot or pick up Medical Supplies off the ground for [QC9703 The Cryo-Core]
Click Galaen's Corpse to turn in [QT9578 Searching for Galaen] and accept [QA9579 Galaen's Fate]
Click Galaen's Journal next to him to accept [QA9706 Galaen's Journal - The Fate of Vindicator Saruan]
Kill Sunhawk enemies for Galaen's Fate [QC9579 Galaen's Fate]
Talk to Scout Joril to turn in [QT10064 Talk to the Hand] and accept [QA10065 Cutting a Path]
Talk to Scout Loryi to accept [QA9741 Critters of the Void] *****
Kill Mutated Tanglers for [QC10066 Oh, the Tangled Webs They Weave] and ravagers for [QC10065 Cutting a Path]
Kill Void Critters for [QC9741 Critters of the Void] *****
Talk to Vindicator Corin to turn in [QT10066 Oh, the Tangled Webs They Weave]
Talk to Scout Jorli to turn in [QT10065 Cutting a Path]
Hearth [H]
Talk to Morae to turn in [QT9579 Galaen's Fate]
Talk to Vindicator Aesom to turn in [QT9741 Critters of the Void]. 
Talk to Vindicator Aesom to accept [QA9753 What We Know...]
Talk to Vindicator Kuros to turn in [QT9703 The Cryo-Core] and [QT9706 Galaen's Journal - The Fate of Vindicator Saruan]. Accept [QA9711 Matis the Cruel].
Talk to Vindicator Aseom to accept [QA9748 Don't Drink the Water]
Talk to Exarch Admetius to turn in [QT9753 What We Know...] and accept [QA9756 What We Don't Know...]
Talk to the Captured Sunhawk Agent for [QC9756 What We Don't Know...]
Talk to Exarch Admetius to turn in [QT9756 What We Don't Know...] and accept [QA9760 Vindicator's Rest]
If you see Matis the Cruel along the road, use the flare gun and kill him for [QC9711 Matis the Cruel]
Talk to Vindicator Corin to turn in [QT9760 Vindicator's Rest]
Kill Fouled Water Spirits for [QC10067 Fouled Water Spirits]
Talk to Researcher Cornelius to accept [QA9670 They're Alive! Maybe...]
Kill Myst Leechers and Myst Spinners for [QC9669,1 The Missing Expedition][O][QC9669,2 The Missing Expedition][O] while doing the next steps
Attack Webbed Creature to hopefully free Expedition Researchers for [QC9670 They're Alive! Maybe...]
Kill Zarakh for [QC9669,3 The Missing Expedition]
Finish up [QC9669 The Missing Expedition]
Talk to Researcher Cornelius to turn in [QT9670 They're Alive! Maybe...]
Talk to Vindicator Corin to turn in [QT10067 Fouled Water Spirits]
Drop down the waterfall and use Water Sample Flask for [QC9748 Don't Drink the Water]
Hearth [H]
Talk to Achelus to turn in [QT9669 The Missing Expedition]
Talk to Vindicator Aesom to turn in [QT9748 Don't Drink the Water]
Talk to Vindicator Kuros to turn in [QT9711 Matis the Cruel]
The rest of the quests are optional and either require a group or a lot of travel.
Fly to [F The Exodar]
[G20.41,54.17,1 Azuremyst Isle] Take the boat to Auberdine
Talk to Thundris Windweaver to turn in [QT9633 The Way to Auberdine] and accept [QA10752 Onward to Ashenvale].
[G36.35,45.57,1 Darkshore] Get Auberdine flight point[P]
[G33.18,40.17,1 Darkshore] Take the boat to Darnassus
[G58.39,93.99,1 Teldrassil] Get Darnassus flight point. [P]
Fly to [F Auberdine]
Head south to Ashenvale.[G42.83,93.11Darkshore]
Talk to Daelyshia to get the flight point.[P][G34.4,47.99,1Ashenvale]
Talk to Raene Wolfrunner to turn in [QT10752 Onward to Ashenvale].
Go here to head to the Barrens and up the mountain.[G69.1,86.9,2Ashenvale][G49,5.3,2The Barrens][G49.3,12.3,2The Barrens][G52.3,6.7The Barrens].
Destroy the Hearthstone in your bag, then go to Support from the in-game menu. Scroll down and choose Stuck Character Service from  the Self-Service Options section, then click Continue. Make sure it says the character will be moved to Westfall, then click Move Character. NOTE - The following steps assume you will get moved to Westfall, however in latest testing the character gets moved outside Stormwind. If you get moved to Stormwind, switch the order of the following two steps.
Talk to Thor to get the flight point.[P][G56.54,52.64,1Westfall]
Talk to Dungar Longdrink to get the flight point.[G66.2,62.4,2Stormwind City][P]
Talk to Innkeeper Allison to make this inn your home.[S][G52.73,65.62Stormwind City]
Talk to Guard Parker to accept [QA244 Encroaching Gnolls].
Talk to Deputy Feldon to turn in [QT244 Encroaching Gnolls] and accept [QA246 Assessing the Threat].
Talk to Ariena Stormfeather to get the flight point.[P][G30.58,59.39,1Redridge Mountains]
Go to Duskwood [G7,89Redridge Mountains]
Talk to Bartender Hann to buy a Bottle of Moonshine for a future quest.[G73.81,44.02,2Duskwood]
Talk to Felicia Maline to get the flight point.[G77.48,44.3,1Duskwood][P]
Fly to [F Redridge Mountains]
Talk to Foreman Oslow to accept [QA125 The Lost Tools].
Talk to Verner Osgood to accept [QA1097 Elmore's Task].[G30.97,47.28,1Redridge Mountains]
Talk to Verner Osgood to accept [QA118 The Price of Shoes].
Talk to Magistrate Solomon to accept [QA120 Messenger to Stormwind].
Talk to Darcy to accept [QA129 A Free Lunch].
Talk to Barkeep Daniels to accept [QA116 Dry Times].
Talk to Shawn to accept [QA3741 Hilary's Necklace].
Click Glinting Mud underwater to complete [QC3741 Hilary's Necklace].
Click Sunken Chest for [QC125 The Lost Tools].
Kill Redridge Poachers and Redridge Mongrels for [QC246 Assessing the Threat].
Talk to Guard Parker to turn in [QT129 A Free Lunch] and accept [QA130 Visit the Herbalist]
Talk to Deputy Feldon to turn in [QT246 Assessing the Threat].
Fly to [F Stormwind]
Talk to Grimand Elmore to turn in [QT1097 Elmore's Task] and accept [QA353 Stormpike's Delivery].[A NightElf]
Talk to Billibug Cogspinner to buy a Bronze Tube.[G55.2,7.1Stormwind City] If he doesn't have one get one from the auction house.
Talk to Roberto Pupellyverbos and buy a Cask of Merlot for [QC116,2 Dry Times].[G52.18,67.82,2Stormwind City]
Talk to General Marcus Jonathan to turn in [QT120 Messenger to Stormwind] and accept [QA121 Messenger to Stormwind].
Go to Goldshire and talk to Barkeep Dobbins to buy a Skin of Sweet Rum for [QC116,4 Dry Times][G43.99,65.68,2Elwynn Forest]
Talk to Smith Argus to turn in [QT118 The Price of Shoes] and accept [QA119 Return to Verner].
Fly to [F Westfall]
[G65,61Westfall] Get 5 Hops from Harvest Reapers around here. [CI1274,5]
Talk to Grimbooze Thunderbrew to accept [QA117 Thunderbrew Lager]. This is repeatable so you will have to mark it complete.
Talk to Grimbooze Thunderbrew again to turn in [QT117 Thunderbrew Lager] since you should have the Hops already. This is repeatable so you will have to mark it complete.
The Keg of Thunderbrew you have is for [QC116,1 Dry Times]
Fly to [F Redridge Mountains]
]], 'Caines Alliance Guides')